
create table tasks (
    id integer generated by default as identity,
    title varchar(255) not null,
    description varchar(255) not null,
    date date not null,
    user_id bigint,
    primary key (id)
);

